# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_tag_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presenca', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
